version: "3"
services:
  app:
    build: .
    container_name: app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - myapp


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_test_db
      MYSQL_USER: serge
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - myapp

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: serge
      PMA_HOST: db
      PMA_PASSWORD: 1234
    networks:
      - myapp

networks:
  myapp: